# h2 설정
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:

gemini:
  api:
    key: testKey
  request:
    uri: https://generativelanguage.googleapis.com
    path: /v1beta/models/gemini-1.5-flash-latest:generateContent

ai:
  prompt:
    max-length-message: ", 답변을 최대한 간결하게 50자 이하로"

jwt:
  secret:
    key: testKeytestKeytestKeytestKeytestKeytestKeytestKe
  access-token-expiration-time: 3600000  # 1시간 (밀리초 단위)
  refresh-token-expiration-time: 604800000  # 7일 (밀리초 단위)
